kind: ConfigMap 
apiVersion: v1 
metadata:
  name: react-frontend-config-g4gp 
data:  
  NEXT_PUBLIC_RAPID_API_KEY: <NEXT_PUBLIC_RAPID_API_KEY>
  NEXT_PUBLIC_REALTY_API_URL: <NEXT_PUBLIC_REALTY_API_URL>
  NEXT_PUBLIC_INFERENCE_URL: <NEXT_PUBLIC_INFERENCE_URL>